package com.tenacity.sopho.domain;

public enum SophoCostCentreType {
	NO_COST_CENTRE,
	NO_VALIDATION,
	MODULO_VALIDATION,
	TABLE_VALIDATION,
	MALICIOUS_CALL_TRACE,
	PID,
	DPNSS_CHARGE_REPORT,
	CHARGING_DIVERSION_INITIATOR
}
